### ISSUE TITLE
NPM Package 1.5.0 contains a breaking change!

### ISSUE THREAD

**Issue by mircodariol** [rmraya/MTEngines#1]
**Bug Description**
There is a breaking change in the constructor of the `GoogleTranslator` object.
In the latest NPM package `1.5.0` the constructor requires one parameter instead of two.

This causes a build error on every application that declares a dependency on `MTEngines` as `"^1.4.0"` and uses the `GoogleTranslator` class because npm installs the `1.5.0` considering that package as backward compatible.

> For example, your application Swordfish now doesn't build any tag from 4.29.0 to the latest 5.4.0.

Can you please un-list version 1.5.0 from NPM and publish it again as 2.x?
Note: you have also not tagged the version in Git repo,

**How to reproduce**
Try to build any version of your application "Swordfish" from tag 4.29.0 to the latest 5.4.0 one.

I really appreciate any help you can provide.

Thanks in advance,

MD

**Comment by rmraya** [comment]
MTEngines `1.5.0` with the new constructor for `GoogleTranslator` is the right dependency for Swordfish 5.5.0, which is the latest official release available at http://maxprograms.com  

Checkout again latest code from https://github.com/rmraya/Swordfish `master` branch. I just modified `package.json` in Swordfish 5.4.0 to install `"mtengines": "1.4.0"` so you can build it.
